# Generated by Django 5.0.3 on 2024-04-12 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bairro',
            fields=[
                ('bairro_id', models.AutoField(primary_key=True, serialize=False)),
                ('bairro', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cep',
            fields=[
                ('cep_id', models.AutoField(primary_key=True, serialize=False)),
                ('cep', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('cidade_id', models.AutoField(primary_key=True, serialize=False)),
                ('cidade', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('endereco_id', models.AutoField(primary_key=True, serialize=False)),
                ('endereco', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('estado_id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('livro_id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=100)),
                ('editora', models.CharField(max_length=100)),
                ('genero', models.CharField(max_length=50)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imagem', models.TextField(max_length=5000)),
                ('descricao', models.TextField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cliente_id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('numero', models.IntegerField()),
                ('complemento', models.CharField(max_length=200)),
                ('telefone', models.CharField(max_length=20)),
                ('celular', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('senha', models.CharField(max_length=100)),
                ('como_soube', models.CharField(max_length=200)),
                ('bairro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.bairro')),
                ('cep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.cep')),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.cidade')),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.endereco')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.estado')),
            ],
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('venda_id', models.AutoField(primary_key=True, serialize=False)),
                ('data_venda', models.DateField()),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='ItemVenda',
            fields=[
                ('itemvenda_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantidade', models.PositiveIntegerField()),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.livro')),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.venda')),
            ],
        ),
    ]
